---
title: "3.Gene_expressions_analysis -  Applying random forests on field data"
author: "Fay Webster"
date: '2022-07-18'
geometry: margin=2cm
output:
  pdf_document: default
  theme: journal
  toc: yes
  toc_float: yes
  html_document: null
  word_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Aim: 
- Applying the models established in the script: 
2.Gene_expression_analysis on the field data.
- How are hybrid mice different to the parental species?

#  Load necessary libraries:

```{r libraries, message = FALSE, warnings = FALSE}
#install.packages("optimx", version = "2021-10.12") # this package is required for 
#the parasite load package to work
library(tidyverse)
library(tidyr)
library(dplyr)
library(cowplot)
library(randomForest)
library(ggplot2)
library(caret)
library(VIM) # visualizing missing data
library(mice) # imputing missing data without predictors
library(ggpubr)
library(optimx)
library(rfUtilities) # Implements a permutation test cross-validation for 
# Random Forests models
```

## Field data

## Importing field data


```{r}
Field <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/SOTA_Data_Product.csv")

```


## Cleaning data 

```{r summary_stats_field}
Field %>% summarise(length(Mouse_ID))
```

We have 1921 mice in total.


#### Prepare columns for selecting

```{r genes}
EqPCR.cols      <- c("delta_ct_cewe_MminusE", "MC.Eimeria", "Ct.Eimeria") #,"Ct.Mus""delta_ct_ilwe_MminusE", )

EimGeno.cols    <- c("n18S_Seq", "COI_Seq", "ORF470_Seq", "eimeriaSpecies")

Gene.Exp.cols   <- c("IFNy",  "CXCR3", "IL.6", #"GBP2", "IL.12", "IRG6",
                     "IL.10", "IL.13", "IL1RN",
                     "CXCR3", "CASP1", "CXCL9", 
                     "IDO1", "IRGM1", "MPO", "MUC2", "MUC5AC", "MYD88", 
                     "NCR1", "PRF1", "RETNLB", "SOCS1", "TICAM1", "TNF")

House.Keeping.cols <- c("GAPDH", "PPIB", "B.actin", "B-actin")
```


#### Cleaning

```{r}
#which are the numbers of the columns of Field
names <- data.frame(colnames(Field))

#how many nas in each column
sapply(Field, function(x) sum(is.na(x)))

f <- Field %>%
  dplyr::select(all_of(Gene.Exp.cols))

#remove rows with only nas
f <- f[rowSums(is.na(f)) != ncol(f), ]

# subset only the rows without any nas everywhere from the first data frame 
Field <- Field[row.names(f), ]

# select columns to be included in imputation
f.1 <- Field %>% dplyr::select(c("Mouse_ID", "Address", "Sex", "Longitude", 
                     "Latitude", "Year", "HI", "HI_NLoci", "mtBamH", "YNPAR", 
                     "X332", "X347", "X65", "Tsx", "Btk", "Syap1", "Es1", 
                     "Gpd1", "Idh1", "Mpi", "Np", "Sod1", "Es1C", "Gpd1C",
                     "Idh1C", "MpiC", "NpC", "Sod1C", "HI_NLoci", "HI", "Zfy2", 
                     "Y", "Region", "Body_Weight", "Body_Length", "Tail_Length",
                     "Fleas", "Ticks", "Ectoparasites_Logical", "Aspiculuris_sp",
                     "Syphacia_sp", "Trichuris_muris", "Taenia_sp",
                     "Heterakis_sp", "Mastophorus_muris", "Hymenolepis_sp", 
                     "Catenotaenia_pusilla", "Heligmosomoides_polygurus", 
                     "Worms_presence", "counter", "Feces_Weight", "Date_count", 
                     "N_oocysts_sq1", "N_oocysts_sq2", "N_oocysts_sq3",  
                     "N_oocysts_sq4", "N_oocysts_sq5", "N_oocysts_sq6", 
                     "N_oocysts_sq7","N_oocysts_sq8", "mean_neubauer", 
                     "delta_ct_ilwe_MminusE", "delta_ct_cewe_MminusE", 
                     "MC.Eimeria", "Ct.Eimeria", "Ct.Mus", "n18S_Seq", 
                     "COI_Seq", "ORF470_Seq", "eimeriaSpecies", "IFNy", 
                     "IL.12", "IRG6", "CXCR3", "IL.6", "GBP2", "IL.10", 
                     "IL.13", "IL.10", "IL.13", "IL1RN", "CXCR3", "CASP1", 
                     "CXCL9","IDO1", "IRGM1", "MPO", "MUC2", "MUC5AC", "MYD88", 
                     "NCR1", "PRF1", "RETNLB", "SOCS1", "TICAM1", "TNF", "GAPDH", 
                     "PPIB", "B.actin", "B-actin","ILWE_Crypto_Ct", 
                     "Oocyst_Predict_Crypto", "ILWE_DNA_Content_ng.microliter",
                      "Treg", "CD4", "Treg17", "Th1", "Th17", "CD8", "Act_CD8", 
                     "IFNy_CD4", "IL17A_CD4", "IFNy_CD8"
                     )

g.1  <- g.1 %>% mutate_if(is.character, as.factor)
g.1  <- g.1 %>% mutate_if(is.integer, as.numeric)

```
